### ISSUE TITLE
Possible bug in the Bait game/Strange semantics of TransformTo.

### ISSUE THREAD

**Issue by mrakgr** [EssexUniversityMCTS/gvgai#19]
On the surface this game appears to work normally, but the semantics of it might be incorrect.

        avatar > MovingAvatar
            nokey > img=alien 
            withkey > img=alien 

Take note that the nokey avatar has the img=alien attribute. Here is snipped from the InteractionSet:

        nokey key > transformTo stype=withkey

This one took me by surprise. At first I thought the avatar was supposed to start as nokey, but it appears that GVGAI InteractionSet semantics work upstream as well as downstream. Is the nokey on the left side really supposed to affect its parent as well? I'd recommend against it as making the effects work upstream make inference more difficult and can potentially introduce bugs.

The reason it surprised me was probably because the singleton attribute does not propagate upstream in SpriteSet.

Edit:

    goal withkey > killSprite scoreChange=5

To drive the point further, if the withkey on the right side propagated upwards, it would be impossible to make this effect work the way it is intended. 

I just want a quick check here whether this upstream propagation on the left side really is standard? I only noticed it for the first time in the Bait game. Also what about collectResources? That particular effect applies on the right side.

**Comment by diegopliebana** [comment]
Regarding Bait (and in general): semantics do NOT work upstream (bugs aside). In the case of Bait, the avatar takes the avatar (that's the blue fellow - alien is pink for an undetermined reason) as image because that's loaded by default in code (in case it's not provided: Game.java, L763). A nice way to check that this is the case is to provide withkey with a different parameter (i.e. speed=0.5) and you can see how the starting avatar does not "inherit" this parameter and speed=1 instead.

This said, it's also true that the definition in this game is quite misleading, also the fact that the avatar does not start as nokey, as it should. This has been fixed.

Regarding CollectResource, it's an effect that actually affects both sprites, as it kills the second sprite by default. This is similar to the way new effect KillBoth affects both sprites on the left and right... so I guess the answer would be that effects do not affect the left side of the interactions in VGDL.
