### ISSUE TITLE
Optimization suggestions (by Dennis Soemers)

### ISSUE THREAD

**Issue by diegopliebana** [EssexUniversityMCTS/gvgai#34]
**1) core.game.Game$Bucket:**

- None of the methods inside the class rely on the lists of sprites in ''spriteLists'' being ordered
- The ''spriteLists'' TreeMap is only exposed to code outside of the class through the getSpriteList() method
- getSpriteList() is only called inside core.game.Game.eventHandling() for the ''first'' and ''second'' variables
	- eventHandling() loops through these ArrayLists to generate events (I think only collision events?). 
	- So, the order in which the ArrayLists are stored in the TreeMap only matters if the order in which the events are generated/executed matters
	- This order is currently determined by y coordinate (see call hierarchy of core.VGDLSprite.bucket)
		- Is that really a useful ordering? 
			- If this order is not actually important, I'd suggest using a HashMap instead of a TreeMap
			- Even if the ordering is considered important, it might be worth trying to store them in a HashMap anyway,
			and then sorting the keySet right before looping through it in eventHandling.
			

**2) core.game.Game.historicEvents:**
- Is the ordering of Events in this collection defined by core.game.Event.compareTo() really important?
- Changing this to an ArrayList instead of a TreeSet would:
	- Not change the ordering of events very much, because they're still added in the correct order with respect
	to game time.
	- Require a change in API (because getEventsHistory() would no longer return a TreeSet)
	- Significantly reduce the processing time required for adding events when advancing states
	- Significantly reduce the processing time required for copying states, because copying states
	also involves iterating over this collection and adding all the elements to a copy of the collection

**3) core.SpriteGroup:**
- Is it necessary for ''sprites'' to be a ConcurrentHashMap? If not, a regular HashMap might be faster?
- An ArrayList instead of any kind of HashMap might be even better:
	- getKeys() is only called by core.game.Game.tick() to iterate through the entire collection, which would
	be faster with an ArrayList
	- Every caller of getSpriteIterator() also uses it to iterate through the entire collection, which would
	be faster with an ArrayList
	- removeSprite() is called by core.game.Game.clearAll() to kill some specific sprites, which would be
	slower with an ArrayList.
	- getSprite() is only called by core.game.Game.tick(), to loop through the entire collection in combination
	with getKeys() (see the point about getKeys() above)
	- getFirstSprite() has two callers that use it to specifically get the ''first'' sprite in the HashMap.
	I suppose it might return a different result with an ArrayList, but this already seems kind of hacky to
	begin with since a ConcurrentHashMap does not have any specific ordering? 

**4) core.game.ForwardModel.updateObservation():**
- I don't believe the ''observations'' map can ever contain a null value
	- So, the observations.containsKey() being followed up by observations.get() is inefficient,
	probably better to immediately do observations.get() and then check for null
	

**5) Entire project:**
- A case-sensitive search for "Integer" through all the files in the project shows a large number of templated
collections using Integer objects, such as ArrayList<Integer>, HashMap<Integer, SomethingElse>, 
TreeMap<Integer, Integer>, Pair<Integer, Integer>, etc.
- Some of these are collections I also mentioned in other points above, some aren't.
- All the wrapping and unwrapping of primitive ints in Integer objects takes a lot of processing time,
and has a lot of memory overhead.
- Replacing these data structures with non-templated variants that work directly using primitive ints,
such as those from the "trove" library, could result in a significant speed increase. Only doing this
for one or two of the collections would probably be premature optimization, but some of them are used very
frequently and all of them added up together is probably signifcant.

**6) No reflection in simulations**
See https://github.com/EssexUniversityMCTS/gvgai/pull/33

**Comment by diegopliebana** [comment]
These optimizations will be implemented in the branch "optimizations", here:

https://github.com/EssexUniversityMCTS/gvgai/tree/optimizations

Comments to each point below, and implementation procedure at the end:

**1) core.game.Game$Bucket:**

Done. I've checked that the behaviour is the same. Performance gain depends on the game (some games actually get worse performance), but average performance gain is about 3.58 (std. err: 1.5) MCTS iterations (depth=10) averaged across all games (minimum "gain": -25 iterations, maximum gain: +50 iterations).

**2) core.game.Game.historicEvents:**

Doable, with care. This might draw some old controllers incompatible. It depends how much and how many controllers this affect. I'll leave this one to be decided in the future.

**3) core.SpriteGroup:**

I'm checking this at the moment. It will be done if performance does not get affected by it.

**4) core.game.ForwardModel.updateObservation():**

Observations map can indeed have null values. What can be done is to retrieve the observation and act accordingly if the value is null. I'm working on this.


** 5) Entire project: ** 
** 6) No reflection in simulations **

The change in the codebase for these two points is large, although point 6 could be interesting to do.

Dennis, you mentioned in the other thread that you observed an improvement in performance for a few games. Would you mind repeating these measurements for all games and levels? With a proper reassurance that it's worth it, and that nothing breaks down, I'm willing to incorporate it to the framework. If you're willing to do this, would you mind making a pull request to the optimizations branch?

Thanks.
Diego.

**Comment by DennisSoemers** [comment]
Do you mean point 6? Yes I can probably have a look at running those experiments in a few days. Not right away since I'm also busy running some experiments of my own for my AI currently. 

About that point, I had to make a change there in the copy() operation of vectors because the framework currently compares some of the vectors defined in ontology.Types.java using the ''=='' operator. I suppose it technically would be better if, instead of the ''hacky'' fix in Vector2d.copy(), those comparisons throughout the framework would instead be changed to use .equals()?

**Comment by diegopliebana** [comment]
Yes, point 6, but also point 5 if you think it's worth it.

At the moment, I'm including the changes for Vector2d cheating prevention. I think I found a way to not make controllers incompatible, it's going through some tests at the moment. I'll push it to master soon, then maybe you can include the equals() call. Which, I guess it makes more sense, yes.

Thanks.

**Comment by DennisSoemers** [comment]
Ok. For point 5, there would in principle be no problem with including a (relatively big) library for that?

I'm currently already using the ''trove4j'' library for a few data structures containing integers in my own agent's code (so I already have the library downloaded and could easily test), but it is quite big: slightly less than 700 java files (it contains lots and lots of highly specialized data structures for all the primitive types in java except for booleans)

Here is the license for that particular library: http://trove.starlight-systems.com/license

**Comment by diegopliebana** [comment]
If that's the only way, I'd prefer not to, to be honest. Let's leave that change for another iteration, then. The one you mentioned in point 6 seems more urgent (and possibly more significant).

Many thanks.

**Comment by DennisSoemers** [comment]
Alright. Would it still be fine if I do include a library of that size in my own agent though?

**Comment by diegopliebana** [comment]
Sure. As long as it is self-content and doesn't need external dependencies, that's fine!

**Comment by DennisSoemers** [comment]
Two more ideas for core.game.Game.eventHandling(). Relatively small ideas, but maybe still useful since that function consistently takes the most time of all functions:

**7) core.game.Game.eventHandling():**
- Intuition: when looking for collisions between dirt objects (in Boulderdash) and the avatar, there is no need to search for a colliding avatar for every dirt object. We know there are many dirt objects and only 1 avatar, so start with the avatar and search for a colliding dirt object for him.
- Implement a swapped version of the ''for(Integer bucket1 : first.keySet())'', where the outer loop goes through sprites of second type instead of the first type
- compare first.size() and second.size(), and use the variant of the loop where the outer loop goes through the smallest set
- I know that in the case of a big set for the outer loop and small sets in the inner loop, the inner loops will typically terminate quickly because there will be many null buckets, but there's still a bunch of code running before the ''spritesInBucket2 != null'' check

**8) core.game.Game.eventHandling():**
- Initially I thought it was quite a waste that all the buckets in bucketList are cleared so frequently inside the loops for all effects (not only pair-collision effects, but also time and EOS effects). At first glance it seems like the data stored inside these buckets should remain correct, but I suppose it is possible that many effects can move, kill, or spawn sprites, and therefore invalidate the contents of buckets after executing events.
- Would it maybe be possible to make a special case for type 0 (the wall type), and not clear those results? I suppose that in many games, the set of  wall sprites is the largest of all sets. Or are there games in which it is possible to manipulate walls too in a manner that would invalidate the
contents of bucketList[0]?

**Comment by DennisSoemers** [comment]
I just thought of something for core.game.Game.Bucket (the very first optimization suggestion). Previously I said that every list was stored in the TreeMap sorted by y-coordinate, which was probably not an important ordering, so a HashMap would work just as well.

However... the y-coordinates are guaranteed to be nice, consecutive integers starting from 0, right? So why not just use an ArrayList? It should provide the same ordering as the original TreeMap in case that is considered to be relevant, and should be much faster than either a TreeMap or a HashMap.

**Comment by DennisSoemers** [comment]
@diegopliebana I was wondering whether you have a specific preference for me to use the sampleMCTSController or the sampleOLMCTSController when testing changes in performance?

I quickly checked and, as expected, both the advance() and the copy() functions use a significant amount of time for sampleMCTSController, whereas the sampleOLMCTSController is much more reliant on advance() and less on copy(). So, the choice of controller will likely have some influence on the results.

**Comment by diegopliebana** [comment]
Hi Dennis,

SampleMCTSController is better, and that's the one I've used in the past to measure this. As it uses those functions more heavily, it should provide a more reliable test and would help to find any problems.

Cheers,
Diego.

**Comment by DennisSoemers** [comment]
I have implemented idea **6**. I some quick experiments it seemed to be a very significant improvement on games like Aliens/Missile Command which spawn many sprites (missiles), and neutral for other games. I am busy running a large-scale test with all games currently, will let you know once that's done.

---

I have also implemented something like idea **7**, to optimize eventHandling(), which seems to be one of the most important methods to optimize according to my profilers. What I did is, I first add sprites to buckets of the type with the lowest number of sprites (typically the avatar), and in that process remember in which rows of the map I found sprite of that first type. Then, when collecting sprites for the second type, I only add them to buckets if they're 1) outside the map or 2) in one of the rows close to rows where sprites of the first type were found (buckets containing sprites of the first type + or - 1 depending on bucketSharp).

In a game like Boulderdash this seems to roughly cut in half the number of times that core.game.Game$Bucket.add is called, which was the number two hot spot before the optimization (with number one being eventHandling()), and only the number four hot spot after the optimization. I will run a large-scale test with all games for this optimization after I'm done with the one that is currently running for idea **6**.

---

I have previously tried implementing idea **5** using only a small number of the files of the huge library I mentioned. It didn't appear to help a lot for performance. However, after what I mentioned above, the number two hot spot is java.lang.Integer.valueOf, with by far the majority of those calls coming from core.game.ForwardModel.updateObservation(). This is probably because both observations.containsKey() and observations.get() need to unwrap the Integer object. So, this hot spot can probably be cut roughly in half if idea **4** can be implemented.

---

The number 3 hot spot is currently tools.Vector2d.<init>, meaning that a significant amount of time is being spent constantly creating new Vector2d objects. Currently 80% of these Vector2d objects are being created by core.VGDLSprite.getPosition(), which in turn is mostly called by core.game.ForwardModel.updateObservation(). Note that I have already changed that method to only call getPosition() once and cache it (it was previously called twice in a row without caching, so in the current official version of the framework it is even worse). So, it may be worth storing a Vector2d object in every VGDLSprite which is modified whenever the rectangle is modified, instead of creating a new Vector2d every time getPosition() is called. Obviously this would increase the cost of copying objects a bit, so it may not help.

---

The number 5 hot spot is java.awt.Rectangle.<init>, meaning that a large number of Rectangle objects is being created. This is mostly from core.VGDLSprite.preMovement(). Wouldn't that method be able to simply modify the existing lastRect object, instead of replacing it with a new one? Additionally, copying VGDLSprites probably also creates too many Rectangle objects. First, init() will be called which creates new instances for rect and lastRect, and then copyTo() is called which again creates new instances for them instead of modifying the ones that have just been created.

---

**Note:** All the data I mentioned above about Hot Spots and other profiler data is from Boulderdash, with a significantly increased amount of processing time per tick because I started using a different (probably better) profiler which does have more overhead (previously VisualVM, now JProfiler). The changes that I already mentioned implementing I am busy to test with all games, though obviously without profiler there.

**Comment by DennisSoemers** [comment]
The attached .zip file contains a pdf with a table of my initial results; avg. MCTS iterations per tick before optimization, and after optimization. The optimization tested here was the one where I tried to reduce the amount of Reflection code running, implemented here; https://github.com/DennisSoemers/gvgai/commit/fd7691c11c0b4c2949d538aa91b91a07d9741d0d

The branch in that fork where I commited also, by now, contains another optimization for which I'm still running the test. 

In the table, I've bolded the highest number in every row, except for in rows where the iteration counts are very close (within ~0.5). It shows the change is an improvement in the vast majority of cases. Also, some of the improvements have a much higher magnitude (sometimes doubling the iteration count for games that had very low iteration counts, and sometimes double-digit improvements for the ones that already had many iterations), whereas the detrimental cases are all still quite close. From a theoretical point of view I can't really think of any reason why the change would ever be detrimental though, wouldn't be surprised if those cases are just variance.

I also have the standard errors printed in my output files, but my output files are not in a very easily parseable format. Anyway, let me know if you still want more of that data.

[GVGAI Optimization Results.zip](https://github.com/EssexUniversityMCTS/gvgai/files/233494/GVGAI.Optimization.Results.zip)

**Comment by DennisSoemers** [comment]
The attached .zip file contains a pdf with a table of my results for the second optimization, the one that I mentioned in the previous post that was still running. This time the left column contains the results of the optimization mentioned in the previous comment, and the right column is the new change on top of that. The new optimization is the one I implemented here: https://github.com/DennisSoemers/gvgai/commit/52651192fc1affca99f2068396d2166f4ac339d7

Again, the majority of the games show improvements, with only some detrimental cases. I also quickly checked how many games there were where the combination of the two optimizations is detrimental, which is 7 games; _Bait, Cookmepasta, Hungrybirds, Intersection, Labyrinth, Modality, Overload_. For all other games the combination of the two optimizations is an improvement (most cases) or about the same (a few of them).

@diegopliebana I do have more data available (also printed the standard errors), so if you'd like me to report more detailed results I can do that. Otherwise, the optimizations are available on my fork, but it does also contain a bunch of other changes I made for testing and printing on my setup. So, if these optimizations seem interesting to merge, I'll have a look tomorrow at undoing any changes that probably should not go back into the official repository and then I'll send a pull request.

[GVGAI Optimization Results 2.zip](https://github.com/EssexUniversityMCTS/gvgai/files/233624/GVGAI.Optimization.Results.2.zip)

**Comment by diegopliebana** [comment]
Hi Dennis,

I've run all the tests and results are pretty solid:

[Optimization-Performances.pdf](https://github.com/EssexUniversityMCTS/gvgai/files/245763/Optimization-Performances.pdf)

At the moment, the changes have been merged in the branch twoPlayersTrack, that will be soon merged into master too. I'll send an email to the group when this is ready as well.

Many thanks for your work on this!

Best,
Diego.
